- alias: Send message on low Leecher4 space
  trigger:
    platform: numeric_state
    entity_id: sensor.disk_use_percent
    above: 75
    for:
      minutes: 15
  action:
  - service: telegram_bot.send_message
    data_template:
      message: Low space on leecher4 @{{now().strftime("%H:%M")}}h!
  id: d54c48a0abb04d348e858fc51796db46
- alias: turn on front door light after sunset
  trigger:
  - platform: sun
    event: sunset
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: light.voordeur
  id: 75ac930a73394278823c971cf06eeffa
- alias: turn off front door light after 0100
  trigger:
  - platform: time
    at: 01:00:00
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: light.voordeur
  id: bb587af3df984391acd76ced6719cbee
- id: '1540710718548'
  alias: poweroff bedroomplug after 07:00
  trigger:
  - at: 07:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.neo_coolcam_power_plug_12a_switch
    service: homeassistant.turn_off
- id: '1540710799377'
  alias: poweron bedroom plug at 22:00
  trigger:
  - at: '22:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.neo_coolcam_power_plug_12a_switch
    service: homeassistant.turn_on
- id: '1585590709999'
  alias: '[SECURITY]: Notify when door opens in the night'
  trigger:
  - entity_id: binary_sensor.neo_front_door
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '23:30:00'
    before: 05:30:00
    condition: time
  action:
  - data_template:
      message: Front door open during the night
    service: telegram_bot.send_message
  - data:
      entity_id: light.woonkamer
      flash: long
    service: light.turn_on
  - delay: '[object Object]'
  - data: {}
    entity_id: light.woonkamer
    service: light.turn_on
- id: '1585590702508'
  alias: Lights On
  description: turn on livingroom and garden lights 1 hour before sunset
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: light.woonkamer
    service: light.turn_on
  - data: {}
    entity_id: light.tuin
    service: light.turn_on
  - data: {}
    entity_id: light.hue_smart_plug_1
    service: light.turn_on
  mode: single
- id: '1585591927256'
  alias: Turn off some garden lights at 23:59
  description: Turn off some garden lights at 23:59
  trigger:
  - at: '23:59'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: light.tuin
    service: light.turn_off
  mode: single
- id: '1585591997639'
  alias: Turn off dinner light at 19:00
  description: ''
  trigger:
  - at: '19:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: light.fibaro_system_fgd212_dimmer_2_level_3
    service: light.turn_off
  mode: single
- id: '1586979948644'
  alias: turn on kitchen lights small in the morning
  description: ''
  trigger:
  - event: sunrise
    offset: -01:00:00
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: light.hue_smart_plug_1
    service: light.turn_on
- id: '1586980249342'
  alias: turn off kitchen light small at night
  description: ''
  trigger:
  - at: 00:00
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: light.hue_smart_plug_1
    service: light.turn_off
- id: '1586980559761'
  alias: turn off kitchen light small after sunrise
  description: ''
  trigger:
  - event: sunrise
    offset: 02:30:00
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: light.hue_smart_plug_1
    service: light.turn_off
- id: '1598898727888'
  alias: Cert Expiry Notification
  description: Send message when certificate is about to expire
  trigger:
  - at: 09:00:00
    platform: time
  condition:
  - below: '7'
    condition: numeric_state
    entity_id: sensor.cert_expiry_avbhome_duckdns_org_8123
  action:
  - data:
      message: SSL cert due to expire in {{ states.sensor.cert_expiry_avbhome_duckdns_org_8123.state
        }} days
    service: telegram_bot.send_message
- id: '1603217116451'
  alias: sonos test
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      delay: 00:00:05
      message: De wasmachine is klaar!
      sonos_entity: Huiskamer
      volume: 0.5
    service: script.1603217549622
