homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

recorder:
  purge_keep_days: 5

# Track the sun
sun:

# Weather prediction

weather:
  - platform: darksky
    name: Home
    api_key: !secret darkskyapi_key

sensor:
  - platform: yr
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
  - platform: nederlandse_spoorwegen
    email: !secret ns_username
    password: !secret ns_password
    routes:
    - name: Noi-Duivendrecht
      from: Laa
      to: Dvd
    - name: Duivendrecht-Noi
      from: Dvd
      to: Laa

# Text to speech
tts:
  - platform: google
    language: 'nl'

cast:
  media_player:
  - host: !secret chromecast

sonos:
  media_player:
    interface_addr: !secret unifihost
    hosts:
      - !secret sonoshost

# Cloud
cloud:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chatid

device_tracker:
  - platform: unifi
    host: !secret unifihost
    username: !secret unifyusername
    password: !secret unifypassword
    ssid_filter:
      - !secret SSID
    verify_ssl: false
    consider_home: 300
    interval_seconds: 10
    track_new_devices: no
  - platform: google_maps
    username: !secret glocmail
    password: !secret glocpass

influxdb:
  host: !secret influxhost
  username: !secret influxuser
  password: !secret influxpassword
  port: 8086
  database: home_assistant
  default_measurement: state
  exclude:
    domains:
      - automation
      - calendar
      - groups
      - light
      - media_player
  tags:
    instance: prod
    source: homeassistant

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key
  polling_interval: 30000  
  device_config_glob:
    "sensor.neo_coolcam_power_plug_12a_exporting":
       ignored: true
    "sensor.neo_*interval*":
       ignored: true
    "sensor.*alarm*":
       ignored: true
    "sensor.neo_*previous*":
       ignored: true
    "sensor.*burglar*":
       ignored: true
    "sensor.*sourcenodeid*":
       ignored: true

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include extraconfig/zones.yaml
